### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by princebett** [rust-nairobi/mini-bank#4]
# Front End Design in Penpot 

## What is penpot ? 

Penpot is an open source design platform competing with like likes of Sketcher or Figma.
It is an online tool although a docker image can be downloaded and hosted locally. 
It supports online collaboration.

If everyone would be on board we could use this as the design platform to make sure the UI 
direction is coherrent. 

## Front end 

Below is a link to a demo of the sign up page.
Other pages can easily be composed using components.

https://design.penpot.app/#/view/c764b0d0-c84b-11ec-ab9e-75f6b8214121?page-id=c764b0d1-c84b-11ec-ab9e-75f6b8214121&section=interactions&index=0&share-id=ae8486b0-c85c-11ec-ab9e-75f6b8214121

> P.S for some reason I cannot share a general link of the penpot team and have to invite people one by one. 
> If anyone would like to help in the design please holla @ Prince Bett in the whatsapp group for an add.

**Comment by charleschege** [comment]
Wow! Didnt know there was an open source alternative to the likes of figma. I am definetly interested

**Comment by princebett** [comment]
Here's a link to the site https://design.penpot.app/#/auth/login

**Comment by princebett** [comment]
@charleschege I have also made you an admin to the team so people could also email you for invites.

**Comment by charleschege** [comment]
I have moved this issue to the mini-bank-frontend repo
